FROM node:24-slim@sha256:61bf992754b4ab288d41cb92c25392195d0035871b4723a0abd30a49dcba356c

WORKDIR /app
COPY package.json yarn.lock* ./
RUN yarn install
COPY . .

EXPOSE 80

ENTRYPOINT ["yarn", "start", "--port", "80", "--host", "0.0.0.0"]
