FROM node:24-slim@sha256:e8e2e91b1378f83c5b2dd15f0247f34110e2fe895f6ca7719dbb780f929368eb

WORKDIR /app
COPY package.json yarn.lock* ./
RUN yarn install
COPY . .

EXPOSE 80

ENTRYPOINT ["yarn", "start", "--port", "80", "--host", "0.0.0.0"]
